"""rename location to location_wkt and nullable width height

Revision ID: 533f734c8506
Revises: cbe9f2e28ac5
Create Date: 2026-03-09 03:45:54.402272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '533f734c8506'
down_revision: Union[str, Sequence[str], None] = 'cbe9f2e28ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('location_wkt', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='拍摄地点经纬度'), schema='photo_story')
    op.alter_column('photo', 'width',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='图片宽度(px)',
               schema='photo_story')
    op.alter_column('photo', 'height',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='图片高度(px)',
               schema='photo_story')
    op.drop_column('photo', 'location', schema='photo_story')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True, comment='拍摄地点经纬度'), schema='photo_story')
    op.alter_column('photo', 'height',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='图片高度(px)',
               schema='photo_story')
    op.alter_column('photo', 'width',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='图片宽度(px)',
               schema='photo_story')
    op.drop_column('photo', 'location_wkt', schema='photo_story')
    # ### end Alembic commands ###
