"""init_database

Revision ID: cbe9f2e28ac5
Revises: 
Create Date: 2026-03-07 19:08:17.775003

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe9f2e28ac5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    schema='auth',
    comment='用户核心表，存储账号及安全凭证'
    )
    op.create_index('ix_user_email_active', 'user', ['email'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_user_name_active', 'user', ['name'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_user_phone_active', 'user', ['phone'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.create_table('refresh_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('refresh_token_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_token_pkey')),
    sa.UniqueConstraint('device_id', name=op.f('refresh_token_device_id_key')),
    sa.UniqueConstraint('token_hash', name=op.f('refresh_token_token_hash_key')),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_refresh_tokens_user_device'),
    schema='auth',
    comment='Refresh Token 存储表，支持多端登录'
    )
    op.create_index(op.f('auth_refresh_token_user_id_idx'), 'refresh_token', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_refresh_tokens_user_expires', 'refresh_token', ['user_id', 'expires_at'], unique=False, schema='auth')
    op.create_table('photo',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('object_key', sa.String(length=500), nullable=False, comment='OSS中的相对路径'),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True, comment='OSS中的缩略图相对路径'),
    sa.Column('width', sa.Integer(), nullable=False, comment='图片宽度(px)'),
    sa.Column('height', sa.Integer(), nullable=False, comment='图片高度(px)'),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='拍摄地点经纬度'),
    sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整的EXIF元数据'),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='拍摄时间（从EXIF提取）'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('photo_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_pkey')),
    schema='photo_story',
    comment='照片表，存储照片文件路径、尺寸、地理位置、EXIF 等元数据'
    )
    op.create_index('ix_photo_object_key', 'photo', ['object_key'], unique=False, schema='photo_story')
    op.create_index('ix_photo_taken_at', 'photo', ['taken_at'], unique=False, schema='photo_story')
    op.create_index('ix_photo_user_id', 'photo', ['user_id'], unique=False, schema='photo_story')
    op.create_table('story',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='故事标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='故事内容（Markdown/富文本）'),
    sa.Column('cover_photo_id', sa.UUID(), nullable=True, comment='封面照片ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photo_story.photo.id'], name=op.f('story_cover_photo_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('story_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_pkey')),
    schema='photo_story',
    comment='故事表，存储用户创作的图文故事内容'
    )
    op.create_index('ix_story_created_at', 'story', ['created_at'], unique=False, schema='photo_story')
    op.create_index('ix_story_title', 'story', ['title'], unique=False, schema='photo_story')
    op.create_index('ix_story_user_id', 'story', ['user_id'], unique=False, schema='photo_story')
    op.create_table('photo_story_m2m',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photo_story.photo.id'], name=op.f('photo_story_m2m_photo_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['photo_story.story.id'], name=op.f('photo_story_m2m_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'photo_id', name=op.f('photo_story_m2m_pkey')),
    schema='photo_story',
    comment='故事与照片的多对多关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_story_m2m', schema='photo_story')
    op.drop_index('ix_story_user_id', table_name='story', schema='photo_story')
    op.drop_index('ix_story_title', table_name='story', schema='photo_story')
    op.drop_index('ix_story_created_at', table_name='story', schema='photo_story')
    op.drop_table('story', schema='photo_story')
    op.drop_index('ix_photo_user_id', table_name='photo', schema='photo_story')
    op.drop_index('ix_photo_taken_at', table_name='photo', schema='photo_story')
    op.drop_index('ix_photo_object_key', table_name='photo', schema='photo_story')
    op.drop_table('photo', schema='photo_story')
    op.drop_index('ix_refresh_tokens_user_expires', table_name='refresh_token', schema='auth')
    op.drop_index(op.f('auth_refresh_token_user_id_idx'), table_name='refresh_token', schema='auth')
    op.drop_table('refresh_token', schema='auth')
    op.drop_index('ix_user_phone_active', table_name='user', schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_user_name_active', table_name='user', schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_user_email_active', table_name='user', schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('user', schema='auth')
    # ### end Alembic commands ###
