"""init auth tables

Revision ID: 59147e544ca1
Revises:
Create Date: 2026-01-21 18:53:08.986547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59147e544ca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key')),
    sa.UniqueConstraint('name', name=op.f('user_name_key')),
    sa.UniqueConstraint('phone', name=op.f('user_phone_key')),
    schema='auth',
    comment='用户核心表，存储账号及安全凭证'
    )
    op.create_index('ix_user_email_active', 'user', ['email'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_user_phone_active', 'user', ['phone'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.create_table('refresh_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('refresh_token_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_token_pkey')),
    sa.UniqueConstraint('device_id', name=op.f('refresh_token_device_id_key')),
    sa.UniqueConstraint('token_hash', name=op.f('refresh_token_token_hash_key')),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_refresh_tokens_user_device'),
    schema='auth',
    comment='Refresh Token 存储表，支持多端登录'
    )
    op.create_index(op.f('auth_refresh_token_user_id_idx'), 'refresh_token', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_refresh_tokens_user_expires', 'refresh_token', ['user_id', 'expires_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_user_expires', table_name='refresh_token', schema='auth')
    op.drop_index(op.f('auth_refresh_token_user_id_idx'), table_name='refresh_token', schema='auth')
    op.drop_table('refresh_token', schema='auth')
    op.drop_index('ix_user_phone_active', table_name='user', schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_user_email_active', table_name='user', schema='auth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('user', schema='auth')
    # ### end Alembic commands ###
