"""add avatar_key to user

Revision ID: aac0445c6189
Revises: 533f734c8506
Create Date: 2026-03-15 00:49:45.164443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac0445c6189'
down_revision: Union[str, Sequence[str], None] = '533f734c8506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_key', sa.String(length=255), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_key', schema='auth')
    # ### end Alembic commands ###
