"""add_video_key_to_photo

Revision ID: f225db269af0
Revises: aac0445c6189
Create Date: 2026-03-15 03:38:54.321803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f225db269af0'
down_revision: Union[str, Sequence[str], None] = 'aac0445c6189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('video_key', sa.String(length=500), nullable=True, comment='动态照片/实况照片的视频文件路径'), schema='photo_story')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'video_key', schema='photo_story')
    # ### end Alembic commands ###
